name: "Check Changes Action"
description: "Check if changes were made in a specific directory."
author: "Jia-Huei Tan"
branding:
  icon: "git-pull-request"
  color: "green"
inputs:
  watch-dir:
    description: "The directory to watch for changes."
    required: true
outputs:
  has-changes:
    description: "Whether the directory has changes."
    value: ${{ steps.check.outputs.has_changes }}
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check changes
      id: check
      shell: /usr/bin/bash --noprofile --norc -o pipefail {0}
      run: |
        WATCH_DIR="${{ inputs.watch-dir }}"

        # Try to get the default branch dynamically, or fall back to 'main'
        default_branch=$(git remote show origin | grep 'HEAD branch' | awk '{print $3}')
        if [ -z "$default_branch" ]; then
        default_branch="main"  # Fallback to 'main' if the default branch cannot be determined
        fi

        # List changes
        all_changes=$(git diff --name-only origin/${default_branch}...HEAD)

        printf '%s\n' "--------- ALL CHANGES ---------"
        printf '%s\n' $all_changes
        printf '%s\n' "-------------------------------"

        # Filter changes
        changes=$(echo "$all_changes" | grep "^${WATCH_DIR}")
        if [ -n "$changes" ]; then
        echo "Changes detected in ${WATCH_DIR} directory."
        echo "has_changes=true" >> $GITHUB_OUTPUT
        else
        echo "No changes in ${WATCH_DIR} directory."
        echo "has_changes=false" >> $GITHUB_OUTPUT
        fi
