name: "Check Changes Action"
description: "Check if changes were made in a list of directories."
author: "Jia-Huei Tan"
branding:
  icon: "git-pull-request"
  color: "green"
inputs:
  watch-dirs:
    description: "Space-delimited list of directories to watch for changes."
    required: true
outputs:
  has-changes:
    description: "Whether any of the directories have changes."
    value: ${{ steps.check.outputs.has_changes }}
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check changes
      id: check
      shell: /usr/bin/bash --noprofile --norc -o pipefail {0}
      run: |
        WATCH_DIRS="${{ inputs.watch-dirs }}"

        # Try to get the default branch dynamically, or fall back to 'main'
        default_branch=$(git remote show origin | grep 'HEAD branch' | awk '{print $3}')
        if [ -z "$default_branch" ]; then
          default_branch="main"  # Fallback to 'main' if the default branch cannot be determined
        fi

        # List changes
        all_changes=$(git diff --name-only origin/${default_branch}...HEAD)

        printf '%s\n' "--------- ALL CHANGES ---------"
        printf '%s\n' $all_changes
        printf '%s\n' "-------------------------------"

        # Initialize a variable to track if any changes are detected
        any_changes_detected=false

        # Iterate over each directory in the space-delimited list
        for WATCH_DIR in $WATCH_DIRS; do
          # Filter changes for the current directory
          changes=$(echo "$all_changes" | grep "^${WATCH_DIR}")
          if [ -n "$changes" ]; then
            echo "Changes detected in ${WATCH_DIR} directory:"
            echo "$changes"
            any_changes_detected=true
          else
            echo "No changes in ${WATCH_DIR} directory."
          fi
        done

        # Set the output based on whether any changes were detected
        if [ "$any_changes_detected" = true ]; then
          echo "has_changes=1" >> $GITHUB_OUTPUT
        else
          echo "has_changes=0" >> $GITHUB_OUTPUT
        fi
